<template>
  <div class="w-full">
    <t-select
        v-model="value"
        clearable
        filterable
        placeholder="请选择图标"
        class="w-full"
        :popup-props="{ overlayClassName: 'icon-select-dropdown' }"
    >
      <template #prefixIcon>
        <component v-if="value && iconMap[value]" :is="iconMap[value]" />
      </template>
      <t-option
          v-for="item in options"
          :key="item.key"
          :label="item.label"
          :value="item.key"
      >
        <div class="select__option_item">
          <span class="gva-icon">
            <component v-if="iconMap[item.key]" :is="iconMap[item.key]" />
          </span>
          <span style="text-align: left">{{ item.label }}</span>
        </div>
      </t-option>
    </t-select>
  </div>
</template>

<script setup>
import { reactive, shallowRef } from 'vue'
import {
  AddIcon,
  AppIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachIcon,
  BackwardIcon,
  BarcodeIcon,
  BookIcon, // 替换 BooksIcon
  BrowseIcon,
  BrowseOffIcon,
  BulletpointIcon,
  CalendarIcon,
  CallIcon,
  CameraIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChatIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckCircleFilledIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleIcon,
  ClearIcon,
  CloseIcon,
  CloseCircleIcon,
  CloseCircleFilledIcon,
  CloudIcon,
  CloudDownloadIcon,
  CloudUploadIcon,
  CodeIcon,
  ControlPlatformIcon,
  CopyIcon,
  CreditcardIcon,
  DashboardIcon,
  DeleteIcon,
  DesktopIcon,
  DiscountIcon,
  DownloadIcon,
  EditIcon,
  EllipsisIcon,
  ErrorIcon,
  ErrorCircleIcon,
  ErrorCircleFilledIcon,
  FileIcon,
  FileAddIcon,
  FileCopyIcon,
  FileExcelIcon,
  FilePdfIcon,
  FilePowerpointIcon,
  FileUnknownIcon,
  FileWordIcon,
  FilterIcon,
  FlagIcon,
  FolderIcon,
  FolderAddIcon,
  FolderOpenIcon,
  FormatHorizontalAlignBottomIcon,
  FormatHorizontalAlignCenterIcon,
  FormatHorizontalAlignTopIcon,
  ForwardIcon,
  FullscreenIcon,
  FullscreenExitIcon,
  GiftIcon,
  HeartIcon,
  HeartFilledIcon,
  HelpIcon,
  HelpCircleIcon,
  HelpCircleFilledIcon,
  HistoryIcon,
  HomeIcon,
  HourglassIcon,
  ImageIcon,
  InfoCircleIcon,
  InfoCircleFilledIcon,
  InternetIcon,
  JumpIcon,
  LaptopIcon,
  LayersIcon,
  LinkIcon,
  LinkUnlinkIcon,
  ListIcon,
  LoadingIcon,
  LocationIcon,
  LockOnIcon,
  LockOffIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  MenuFoldIcon,
  MenuUnfoldIcon,
  MinusIcon,
  MinusCircleIcon,
  MinusCircleFilledIcon,
  MobileIcon,
  MobileVibrateIcon,
  MoreIcon,
  MoveIcon,
  NextIcon,
  NotificationIcon,
  NotificationFilledIcon,
  OrderAscendingIcon,
  OrderDescendingIcon,
  PageFirstIcon,
  PageLastIcon,
  PauseIcon,
  PauseCircleIcon,
  PauseCircleFilledIcon,
  PinIcon,
  PlayIcon,
  PlayCircleIcon,
  PlayCircleFilledIcon,
  PlusIcon,
  PoweroffIcon,
  PreciseMonitorIcon,
  PreviousIcon,
  PrintIcon,
  QrcodeIcon,
  QueueIcon,
  RectangleIcon,
  RefreshIcon,
  RemoveIcon,
  RollbackIcon,
  RootListIcon,
  RotateIcon,
  SaveIcon,
  ScanIcon,
  SearchIcon,
  SecuredIcon,
  ServerIcon,
  ServiceIcon,
  SettingIcon,
  ShareIcon,
  ShopIcon,
  SlashIcon,
  SoundIcon,
  StarIcon,
  StarFilledIcon,
  StopIcon,
  StopCircleIcon,
  StopCircleFilledIcon,
  SwapIcon,
  SystemCodeIcon,
  TaskIcon,
  TaskAddIcon,
  TaskCheckedIcon,
  TaskErrorIcon,
  TerminalIcon,
  TerminalWindowIcon,
  ThumbDownIcon,
  ThumbUpIcon,
  TimeIcon,
  TimeFilledIcon,
  TipsIcon,
  ToolsIcon,
  TranslateIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  UnfoldLessIcon,
  UnfoldMoreIcon,
  UploadIcon,
  UsbIcon,
  UserIcon,
  UserAddIcon,
  UserAvatarIcon,
  UserCircleIcon,
  UserClearIcon,
  UsergroupIcon,
  UserListIcon,
  UserTalkIcon,
  VideoIcon,
  ViewColumnIcon,
  ViewListIcon,
  ViewModuleIcon,
  WalletIcon,
  WifiIcon,
  WindowIcon,
  ZoomInIcon,
  ZoomOutIcon
} from 'tdesign-icons-vue-next'

defineOptions({
  name: 'Icon'
})

const value = defineModel()

// 创建图标映射
const iconMap = shallowRef({
  'add': AddIcon,
  'app': AppIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-up': ArrowUpIcon,
  'attach': AttachIcon,
  'backward': BackwardIcon,
  'barcode': BarcodeIcon,
  'blockchain': LinkIcon,
  'books': BookIcon,
  'browse': BrowseIcon,
  'browse-off': BrowseOffIcon,
  'bulletpoint': BulletpointIcon,
  'calendar': CalendarIcon,
  'call': CallIcon,
  'camera': CameraIcon,
  'caret-down': CaretDownIcon,
  'caret-left': CaretLeftIcon,
  'caret-right': CaretRightIcon,
  'caret-up': CaretUpIcon,
  'center-text': FormatHorizontalAlignCenterIcon,
  'chat': ChatIcon,
  'check': CheckIcon,
  'check-circle': CheckCircleIcon,
  'check-circle-filled': CheckCircleFilledIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'circle': CircleIcon,
  'clear': ClearIcon,
  'close': CloseIcon,
  'close-circle': CloseCircleIcon,
  'close-circle-filled': CloseCircleFilledIcon,
  'cloud': CloudIcon,
  'cloud-download': CloudDownloadIcon,
  'cloud-upload': CloudUploadIcon,
  'code': CodeIcon,
  'cog': SettingIcon,
  'component': AppIcon,
  'control-platform': ControlPlatformIcon,
  'copy': CopyIcon,
  'creditcard': CreditcardIcon,
  'dashboard': DashboardIcon,
  'delete': DeleteIcon,
  'desktop': DesktopIcon,
  'discount': DiscountIcon,
  'download': DownloadIcon,
  'edit': EditIcon,
  'ellipsis': EllipsisIcon,
  'email': MailIcon, // 使用 MailIcon 替代
  'error': ErrorIcon,
  'error-circle': ErrorCircleIcon,
  'error-circle-filled': ErrorCircleFilledIcon,
  'file': FileIcon,
  'file-add': FileAddIcon,
  'file-copy': FileCopyIcon,
  'file-excel': FileExcelIcon,
  'file-pdf': FilePdfIcon,
  'file-powerpoint': FilePowerpointIcon,
  'file-unknown': FileUnknownIcon,
  'file-word': FileWordIcon,
  'filter': FilterIcon,
  'flag': FlagIcon,
  'folder': FolderIcon,
  'folder-add': FolderAddIcon,
  'folder-open': FolderOpenIcon,
  'format-horizontal-align-bottom': FormatHorizontalAlignBottomIcon,
  'format-horizontal-align-center': FormatHorizontalAlignCenterIcon,
  'format-horizontal-align-top': FormatHorizontalAlignTopIcon,
  'forward': ForwardIcon,
  'fullscreen': FullscreenIcon,
  'fullscreen-exit': FullscreenExitIcon,
  'gift': GiftIcon,
  'heart': HeartIcon,
  'heart-filled': HeartFilledIcon,
  'help': HelpIcon,
  'help-circle': HelpCircleIcon,
  'help-circle-filled': HelpCircleFilledIcon,
  'history': HistoryIcon,
  'home': HomeIcon,
  'hourglass': HourglassIcon,
  'image': ImageIcon,
  'info': InfoCircleIcon,
  'info-circle': InfoCircleIcon,
  'info-circle-filled': InfoCircleFilledIcon,
  'internet': InternetIcon,
  'jump': JumpIcon,
  'laptop': LaptopIcon,
  'layers': LayersIcon,
  'link': LinkIcon,
  'link-unlink': LinkUnlinkIcon,
  'list': ListIcon,
  'loading': LoadingIcon,
  'location': LocationIcon,
  'lock-on': LockOnIcon,
  'lock-off': LockOffIcon,
  'login': LoginIcon,
  'logout': LogoutIcon,
  'mail': MailIcon,
  'menu-fold': MenuFoldIcon,
  'menu-unfold': MenuUnfoldIcon,
  'minus': MinusIcon,
  'minus-circle': MinusCircleIcon,
  'minus-circle-filled': MinusCircleFilledIcon,
  'mobile': MobileIcon,
  'mobile-vibrate': MobileVibrateIcon,
  'money-circle': CreditcardIcon,
  'more': MoreIcon,
  'move': MoveIcon,
  'next': NextIcon,
  'notification': NotificationIcon,
  'notification-filled': NotificationFilledIcon,
  'order-ascending': OrderAscendingIcon,
  'order-descending': OrderDescendingIcon,
  'page-first': PageFirstIcon,
  'page-last': PageLastIcon,
  'pause': PauseIcon,
  'pause-circle': PauseCircleIcon,
  'pause-circle-filled': PauseCircleFilledIcon,
  'photo': ImageIcon,
  'pin': PinIcon,
  'play': PlayIcon,
  'play-circle': PlayCircleIcon,
  'play-circle-filled': PlayCircleFilledIcon,
  'plus': PlusIcon,
  'poweroff': PoweroffIcon,
  'precise-monitor': PreciseMonitorIcon,
  'previous': PreviousIcon,
  'print': PrintIcon,
  'qrcode': QrcodeIcon,
  'queue': QueueIcon,
  'rectangle': RectangleIcon,
  'refresh': RefreshIcon,
  'remove': RemoveIcon,
  'rollback': RollbackIcon,
  'root-list': RootListIcon,
  'rotate': RotateIcon,
  'save': SaveIcon,
  'scan': ScanIcon,
  'search': SearchIcon,
  'secured': SecuredIcon,
  'server': ServerIcon,
  'service': ServiceIcon,
  'setting': SettingIcon,
  'share': ShareIcon,
  'shop': ShopIcon,
  'slash': SlashIcon,
  'sound': SoundIcon,
  'star': StarIcon,
  'star-filled': StarFilledIcon,
  'stop': StopIcon,
  'stop-circle': StopCircleIcon,
  'stop-circle-filled': StopCircleFilledIcon,
  'swap': SwapIcon,
  'system-code': SystemCodeIcon,
  'task': TaskIcon,
  'task-add': TaskAddIcon,
  'task-checked': TaskCheckedIcon,
  'task-error': TaskErrorIcon,
  'terminal': TerminalIcon,
  'terminal-window': TerminalWindowIcon,
  'text': FileIcon,
  'thumb-down': ThumbDownIcon,
  'thumb-up': ThumbUpIcon,
  'time': TimeIcon,
  'time-filled': TimeFilledIcon,
  'tips': TipsIcon,
  'tools': ToolsIcon,
  'translate': TranslateIcon,
  'tree-list': ListIcon,
  'trending-down': TrendingDownIcon,
  'trending-up': TrendingUpIcon,
  'unfold-less': UnfoldLessIcon,
  'unfold-more': UnfoldMoreIcon,
  'upload': UploadIcon,
  'usb': UsbIcon,
  'user': UserIcon,
  'user-add': UserAddIcon,
  'user-avatar': UserAvatarIcon,
  'user-circle': UserCircleIcon,
  'user-clear': UserClearIcon,
  'user-group': UsergroupIcon,
  'user-list': UserListIcon,
  'user-talk': UserTalkIcon,
  'video': VideoIcon,
  'view-column': ViewColumnIcon,
  'view-list': ViewListIcon,
  'view-module': ViewModuleIcon,
  'wallet': WalletIcon,
  'wifi': WifiIcon,
  'window': WindowIcon,
  'zoom-in': ZoomInIcon,
  'zoom-out': ZoomOutIcon
})

// 图标选项列表
const options = reactive([
  { key: 'add', label: '添加' },
  { key: 'app', label: '应用' },
  { key: 'arrow-down', label: '向下箭头' },
  { key: 'arrow-left', label: '向左箭头' },
  { key: 'arrow-right', label: '向右箭头' },
  { key: 'arrow-up', label: '向上箭头' },
  { key: 'attach', label: '附件' },
  { key: 'backward', label: '后退' },
  { key: 'barcode', label: '条形码' },
  { key: 'blockchain', label: '链接/区块链' },
  { key: 'books', label: '书籍' },
  { key: 'browse', label: '浏览' },
  { key: 'browse-off', label: '隐藏' },
  { key: 'bulletpoint', label: '项目符号' },
  { key: 'calendar', label: '日历' },
  { key: 'call', label: '电话' },
  { key: 'camera', label: '相机' },
  { key: 'caret-down', label: '下拉' },
  { key: 'caret-left', label: '左拉' },
  { key: 'caret-right', label: '右拉' },
  { key: 'caret-up', label: '上拉' },
  { key: 'center-text', label: '居中对齐' },
  { key: 'chat', label: '聊天' },
  { key: 'check', label: '选中' },
  { key: 'check-circle', label: '圆形选中' },
  { key: 'check-circle-filled', label: '圆形选中填充' },
  { key: 'chevron-down', label: '向下' },
  { key: 'chevron-left', label: '向左' },
  { key: 'chevron-right', label: '向右' },
  { key: 'chevron-up', label: '向上' },
  { key: 'circle', label: '圆形' },
  { key: 'clear', label: '清除' },
  { key: 'close', label: '关闭' },
  { key: 'close-circle', label: '圆形关闭' },
  { key: 'close-circle-filled', label: '圆形关闭填充' },
  { key: 'cloud', label: '云' },
  { key: 'cloud-download', label: '云下载' },
  { key: 'cloud-upload', label: '云上传' },
  { key: 'code', label: '代码' },
  { key: 'cog', label: '设置/齿轮' },
  { key: 'component', label: '组件/应用' },
  { key: 'control-platform', label: '控制台' },
  { key: 'copy', label: '复制' },
  { key: 'creditcard', label: '信用卡' },
  { key: 'dashboard', label: '仪表盘' },
  { key: 'delete', label: '删除' },
  { key: 'desktop', label: '桌面' },
  { key: 'discount', label: '折扣' },
  { key: 'download', label: '下载' },
  { key: 'edit', label: '编辑' },
  { key: 'ellipsis', label: '更多' },
  { key: 'email', label: '邮件' },
  { key: 'error', label: '错误' },
  { key: 'error-circle', label: '圆形错误' },
  { key: 'error-circle-filled', label: '圆形错误填充' },
  { key: 'file', label: '文件' },
  { key: 'file-add', label: '添加文件' },
  { key: 'file-copy', label: '复制文件' },
  { key: 'file-excel', label: 'Excel文件' },
  { key: 'file-pdf', label: 'PDF文件' },
  { key: 'file-powerpoint', label: 'PPT文件' },
  { key: 'file-unknown', label: '未知文件' },
  { key: 'file-word', label: 'Word文件' },
  { key: 'filter', label: '筛选' },
  { key: 'flag', label: '旗帜' },
  { key: 'folder', label: '文件夹' },
  { key: 'folder-add', label: '添加文件夹' },
  { key: 'folder-open', label: '打开文件夹' },
  { key: 'format-horizontal-align-bottom', label: '底部对齐' },
  { key: 'format-horizontal-align-center', label: '居中对齐' },
  { key: 'format-horizontal-align-top', label: '顶部对齐' },
  { key: 'forward', label: '前进' },
  { key: 'fullscreen', label: '全屏' },
  { key: 'fullscreen-exit', label: '退出全屏' },
  { key: 'gift', label: '礼物' },
  { key: 'heart', label: '心形' },
  { key: 'heart-filled', label: '心形填充' },
  { key: 'help', label: '帮助' },
  { key: 'help-circle', label: '圆形帮助' },
  { key: 'help-circle-filled', label: '圆形帮助填充' },
  { key: 'history', label: '历史' },
  { key: 'home', label: '首页' },
  { key: 'hourglass', label: '沙漏' },
  { key: 'image', label: '图片' },
  { key: 'info', label: '信息' },
  { key: 'info-circle', label: '圆形信息' },
  { key: 'info-circle-filled', label: '圆形信息填充' },
  { key: 'internet', label: '互联网' },
  { key: 'jump', label: '跳转' },
  { key: 'laptop', label: '笔记本' },
  { key: 'layers', label: '图层' },
  { key: 'link', label: '链接' },
  { key: 'link-unlink', label: '断开链接' },
  { key: 'list', label: '列表' },
  { key: 'loading', label: '加载' },
  { key: 'location', label: '位置' },
  { key: 'lock-on', label: '锁定' },
  { key: 'lock-off', label: '解锁' },
  { key: 'login', label: '登录' },
  { key: 'logout', label: '登出' },
  { key: 'mail', label: '邮件' },
  { key: 'menu-fold', label: '收起菜单' },
  { key: 'menu-unfold', label: '展开菜单' },
  { key: 'minus', label: '减号' },
  { key: 'minus-circle', label: '圆形减号' },
  { key: 'minus-circle-filled', label: '圆形减号填充' },
  { key: 'mobile', label: '手机' },
  { key: 'mobile-vibrate', label: '手机震动' },
  { key: 'money-circle', label: '金钱/信用卡' },
  { key: 'more', label: '更多' },
  { key: 'move', label: '移动' },
  { key: 'next', label: '下一个' },
  { key: 'notification', label: '通知' },
  { key: 'notification-filled', label: '通知填充' },
  { key: 'order-ascending', label: '升序' },
  { key: 'order-descending', label: '降序' },
  { key: 'page-first', label: '第一页' },
  { key: 'page-last', label: '最后一页' },
  { key: 'pause', label: '暂停' },
  { key: 'pause-circle', label: '圆形暂停' },
  { key: 'pause-circle-filled', label: '圆形暂停填充' },
  { key: 'photo', label: '照片/图片' },
  { key: 'pin', label: '图钉' },
  { key: 'play', label: '播放' },
  { key: 'play-circle', label: '圆形播放' },
  { key: 'play-circle-filled', label: '圆形播放填充' },
  { key: 'plus', label: '加号' },
  { key: 'poweroff', label: '关机' },
  { key: 'precise-monitor', label: '精确监控' },
  { key: 'previous', label: '上一个' },
  { key: 'print', label: '打印' },
  { key: 'qrcode', label: '二维码' },
  { key: 'queue', label: '队列' },
  { key: 'rectangle', label: '矩形' },
  { key: 'refresh', label: '刷新' },
  { key: 'remove', label: '移除' },
  { key: 'rollback', label: '回滚' },
  { key: 'root-list', label: '根列表' },
  { key: 'rotate', label: '旋转' },
  { key: 'save', label: '保存' },
  { key: 'scan', label: '扫描' },
  { key: 'search', label: '搜索' },
  { key: 'secured', label: '安全' },
  { key: 'server', label: '服务器' },
  { key: 'service', label: '服务' },
  { key: 'setting', label: '设置' },
  { key: 'share', label: '分享' },
  { key: 'shop', label: '商店' },
  { key: 'slash', label: '斜线' },
  { key: 'sound', label: '声音' },
  { key: 'star', label: '星形' },
  { key: 'star-filled', label: '星形填充' },
  { key: 'stop', label: '停止' },
  { key: 'stop-circle', label: '圆形停止' },
  { key: 'stop-circle-filled', label: '圆形停止填充' },
  { key: 'swap', label: '交换' },
  { key: 'system-code', label: '系统代码' },
  { key: 'task', label: '任务' },
  { key: 'task-add', label: '添加任务' },
  { key: 'task-checked', label: '完成任务' },
  { key: 'task-error', label: '任务错误' },
  { key: 'terminal', label: '终端' },
  { key: 'terminal-window', label: '终端窗口' },
  { key: 'text', label: '文本/文档' },
  { key: 'thumb-down', label: '踩' },
  { key: 'thumb-up', label: '赞' },
  { key: 'time', label: '时间' },
  { key: 'time-filled', label: '时间填充' },
  { key: 'tips', label: '提示' },
  { key: 'tools', label: '工具' },
  { key: 'translate', label: '翻译' },
  { key: 'tree-list', label: '树形列表' },
  { key: 'trending-down', label: '下降趋势' },
  { key: 'trending-up', label: '上升趋势' },
  { key: 'unfold-less', label: '收起' },
  { key: 'unfold-more', label: '展开' },
  { key: 'upload', label: '上传' },
  { key: 'usb', label: 'USB' },
  { key: 'user', label: '用户' },
  { key: 'user-add', label: '添加用户' },
  { key: 'user-avatar', label: '用户头像' },
  { key: 'user-circle', label: '用户圆形' },
  { key: 'user-clear', label: '清除用户' },
  { key: 'user-group', label: '用户组' },
  { key: 'user-list', label: '用户列表' },
  { key: 'user-talk', label: '用户对话' },
  { key: 'video', label: '视频' },
  { key: 'view-column', label: '列视图' },
  { key: 'view-list', label: '列表视图' },
  { key: 'view-module', label: '模块视图' },
  { key: 'wallet', label: '钱包' },
  { key: 'wifi', label: 'WiFi' },
  { key: 'window', label: '窗口' },
  { key: 'zoom-in', label: '放大' },
  { key: 'zoom-out', label: '缩小' }
])
</script>

<style lang="scss">
.gva-icon {
  color: rgb(132, 146, 166);
  font-size: 16px;
  margin-right: 10px;
  display: inline-flex;
  align-items: center;
}

.select__option_item {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  width: 100%;
}

// 图标选择器下拉框样式
:global(.icon-select-dropdown) {
  .t-select-option {
    padding: 8px 12px;

    &:hover {
      .gva-icon {
        color: var(--td-brand-color);
      }
    }
  }
}

// 选中项的前缀图标样式
.t-select .t-input__prefix-icon {
  color: rgb(132, 146, 166);
}
</style>